server:
  port: 8090
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://localhost:5432/integrate_online_shop
    username: postgres
    password: postgres